# Generated by Django 6.0.2 on 2026-05-04 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_exercise_correct_option_exercise_exercise_type_and_more'),
        ('progress', '0002_lessonprogress_resume_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonprogress',
            name='video_watched',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ExerciseAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, max_length=1)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_answers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resposta de Exercício',
                'verbose_name_plural': 'Respostas de Exercícios',
                'unique_together': {('user', 'exercise')},
            },
        ),
    ]
