# Generated by Django 6.0.2 on 2026-04-28 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_emails', models.BooleanField(default=True)),
                ('study_reminders', models.BooleanField(default=True)),
                ('new_lessons', models.BooleanField(default=False)),
                ('achievements_unlocked', models.BooleanField(default=True)),
                ('newsletters', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configurações de Notificação',
                'verbose_name_plural': 'Configurações de Notificação',
            },
        ),
        migrations.CreateModel(
            name='PlaybackSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoplay', models.BooleanField(default=True)),
                ('default_captions', models.BooleanField(default=False)),
                ('video_quality', models.CharField(choices=[('auto', 'Auto'), ('1080p', '1080p'), ('720p', '720p'), ('480p', '480p'), ('360p', '360p')], default='720p', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playback_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configurações de Reprodução',
                'verbose_name_plural': 'Configurações de Reprodução',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('instrument', models.CharField(blank=True, choices=[('violao', 'Violão'), ('guitarra', 'Guitarra'), ('piano', 'Piano / Teclado'), ('baixo', 'Baixo'), ('bateria', 'Bateria / Percussão'), ('voz', 'Voz / Canto'), ('outro', 'Outro')], max_length=20)),
                ('level', models.CharField(choices=[('iniciante', 'Iniciante'), ('basico', 'Básico'), ('intermediario', 'Intermediário'), ('avancado', 'Avançado')], default='iniciante', max_length=20)),
                ('goal', models.CharField(blank=True, choices=[('hobby', 'Tocar por hobby'), ('profissional', 'Me tornar profissional'), ('producao', 'Produzir minhas músicas'), ('teoria', 'Aprender teoria musical')], max_length=20)),
                ('plan', models.CharField(choices=[('free', 'Gratuito'), ('pro', 'Pro')], default='free', max_length=10)),
                ('is_public', models.BooleanField(default=False)),
                ('share_usage_data', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
    ]
