# Generated by Django 6.0.2 on 2026-04-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='correct_option',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1),
        ),
        migrations.AddField(
            model_name='exercise',
            name='exercise_type',
            field=models.CharField(choices=[('practice', 'Prática'), ('quiz', 'Múltipla Escolha')], default='practice', max_length=10),
        ),
        migrations.AddField(
            model_name='exercise',
            name='option_a',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='exercise',
            name='option_b',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='exercise',
            name='option_c',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='exercise',
            name='option_d',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
