# Generated by Django 6.0.2 on 2026-05-04 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_exercise_correct_option_exercise_exercise_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='roteiro',
            field=models.TextField(blank=True),
        ),
    ]
