# Generated by Django 6.0.2 on 2026-05-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_roteiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file_1080p',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/1080p/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file_360p',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/360p/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file_480p',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/480p/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_file_720p',
            field=models.FileField(blank=True, null=True, upload_to='lessons/videos/720p/'),
        ),
    ]
